% Copyright (C) 2020 Frank E. Curtis
%
% All Rights Reserved.
%
% Authors: Frank E. Curtis

% StochasticSQP: printHeader
function printHeader(S,P)

% Print software name
S.reporter_.printf(Enumerations.R_SOLVER,Enumerations.R_BASIC,...
  ['+---------------------------------------------------------------------+\n'...
  '|                             StochasticSQP                           |\n'...
  '| StochasticSQP is released as open source code under the MIT License |\n'...
  '+---------------------------------------------------------------------+\n'...
  '\n'...
  'This is StochasticSQP version 0.1.0\n'...
  '\n']);

% Print problem information
S.reporter_.printf(Enumerations.R_SOLVER,Enumerations.R_BASIC,...
  ['Problem name...................... : %s\n'...
  'Number of variables............... : %8d\n'...
  'Number of equality constraints.... : %8d\n'...
  'Number of inequality constraints.. : %8d\n'...
  '\n\n'],...
  P.name,...
  P.numberOfVariables,...
  P.numberOfConstraintsEqualities,...
  P.numberOfConstraintsInequalities);

% Print header information
S.reporter_.printf(Enumerations.R_SOLVER,Enumerations.R_BASIC,...
  ['Direction computation............. : %s\n'...
  'Merit parameter computation....... : %s\n'...
  'Lipschitz constant estimation..... : %s\n'...
  'Stepsize computation.............. : %s\n'...
  '\n'],...
  S.strategies_.directionComputation.name,...
  S.strategies_.meritParameterComputation.name,...
  S.strategies_.lipschitzEstimation.name,...
  S.strategies_.stepsizeComputation.name);

end % printHeader