% Copyright (C) 2020 Frank E. Curtis
%
% All Rights Reserved.
%
% Authors: Frank E. Curtis

% StochasticSQP: printFooter
function printFooter(S)

% Print termination message
switch S.status_
  case Enumerations.S_UNSET
    S.reporter_.printf(Enumerations.R_SOLVER,Enumerations.R_BASIC,...
      '\nEXIT: Status unset!\n\n');
  case Enumerations.S_SUCCESS
    S.reporter_.printf(Enumerations.R_SOLVER,Enumerations.R_BASIC,...
      '\nEXIT: Stationary point found.\n\n');
  case Enumerations.S_ITERATION_LIMIT
    S.reporter_.printf(Enumerations.R_SOLVER,Enumerations.R_BASIC,...
      '\nEXIT: Iteration limit exceeded.\n\n');
  otherwise
    S.reporter_.printf(Enumerations.R_SOLVER,Enumerations.R_BASIC,...
      '\nEXIT: Status unknown!\n\n');
end % switch

% Print quantities footer
S.reporter_.printf(Enumerations.R_SOLVER,Enumerations.R_BASIC,...
  ['Objective...................... : %+e\n'...
  'Objective (unscaled)........... : %+e\n'...
  'Constraint violation........... : %+e\n'...
  'Constraint violation (unscaled) : %+e\n'...
  'Stationarity measure........... : %+e\n\n'...
  'Iterations..................... : %d\n'...
  'Inner iterations............... : %d\n'...
  'Objective function evaluations. : %d\n'...
  'Objective gradient evaluations. : %d\n'...
  'Constraint function evaluations : %d\n'...
  'Constraint Jacobian evaluations : %d\n\n'...
  'CPU seconds.................... : %d\n'],...
  S.quantities_.currentIterate.objectiveFunction(S.quantities_),...
  S.quantities_.currentIterate.objectiveFunctionUnscaled(S.quantities_),...
  S.quantities_.currentIterate.constraintNormInf(S.quantities_),...
  S.quantities_.currentIterate.constraintNormInfUnscaled(S.quantities_),...
  S.quantities_.currentIterate.stationarityMeasure(S.quantities_,S.quantities_.multiplier),...
  S.quantities_.iterationCounter,...
  S.quantities_.totalInnerIterationCounter,...
  S.quantities_.objectiveFunctionEvaluationCounter,...
  S.quantities_.objectiveGradientEvaluationCounter,...
  S.quantities_.constraintFunctionEvaluationCounter,...
  S.quantities_.constraintJacobianEvaluationCounter,...
  S.quantities_.CPUTime);

end % printFooter