% Copyright (C) 2020 Frank E. Curtis
%
% All Rights Reserved.
%
% Authors: Frank E. Curtis

% StochasticSQP: printFooter
function printFooter(S)

% Print termination message
switch S.status_
  case Enumerations.S_UNSET
    S.reporter_.printf(Enumerations.R_SOLVER,Enumerations.R_BASIC,...
      '\nEXIT: Status unset!\n\n');
  case Enumerations.S_SUCCESS
    S.reporter_.printf(Enumerations.R_SOLVER,Enumerations.R_BASIC,...
      '\nEXIT: Stationary point found.\n\n');
  case Enumerations.S_SIZE_LIMIT
    S.reporter_.printf(Enumerations.R_SOLVER,Enumerations.R_BASIC,...
      '\nEXIT: Size limit exceeded.\n\n');
  case Enumerations.S_ITERATION_LIMIT
    S.reporter_.printf(Enumerations.R_SOLVER,Enumerations.R_BASIC,...
      '\nEXIT: Iteration limit exceeded.\n\n');
  case Enumerations.S_INNER_ITERATION_LIMIT
    S.reporter_.printf(Enumerations.R_SOLVER,Enumerations.R_BASIC,...
      '\nEXIT: Inner iteration limit exceeded.\n\n');
  case Enumerations.S_DIRECTION_COMPUTATION_FAILURE
    S.reporter_.printf(Enumerations.R_SOLVER,Enumerations.R_BASIC,...
      '\nEXIT: Direction computation failure.\n\n');
  case Enumerations.S_CPU_TIME_LIMIT
    S.reporter_.printf(Enumerations.R_SOLVER,Enumerations.R_BASIC,...
      '\nEXIT: CPU time limit exceeded.\n\n');
  case Enumerations.S_OPTIMALITY_PROGRESS_FAILURE
    S.reporter_.printf(Enumerations.R_SOLVER,Enumerations.R_BASIC,...
      '\nEXIT: Optimality improvement is not enough.\n\n');
  case Enumerations.S_FEASIBILITY_PROGRESS_FAILURE
    S.reporter_.printf(Enumerations.R_SOLVER,Enumerations.R_BASIC,...
      '\nEXIT: Feasibility improvement is not enough.\n\n');
  otherwise
    S.reporter_.printf(Enumerations.R_SOLVER,Enumerations.R_BASIC,...
      '\nEXIT: Status unknown!\n\n');
end % switch

% Print quantities footer
S.reporter_.printf(Enumerations.R_SOLVER,Enumerations.R_BASIC,...
  ['Objective......................... : %+e\n'...
  'Objective (unscaled).............. : %+e\n'...
  'Constraint violation.............. : %+e\n'...
  'Constraint violation (unscaled)... : %+e\n'...
  'KKT error......................... : %+e\n'...
  'KKT error (true).................. : %+e\n\n'...
  'Iterations........................ : %d\n'...
  'Inner iterations.................. : %d\n'...
  'Objective function evaluations.... : %d\n'...
  'Objective gradient evaluations.... : %d\n'...
  'Equality function evaluations..... : %d\n'...
  'Inequality function evaluations... : %d\n'...
  'Equality Jacobian evaluations..... : %d\n'...
  'Inequality Jacobian evaluations... : %d\n\n'...
  'CPU seconds....................... : %d\n'],...
  S.quantities_.currentIterate.objectiveFunction(S.quantities_),...
  S.quantities_.currentIterate.objectiveFunctionUnscaled(S.quantities_),...
  S.quantities_.currentIterate.constraintNormInf(S.quantities_),...
  S.quantities_.currentIterate.constraintNormInfUnscaled(S.quantities_),...
  S.quantities_.currentIterate.KKTError(S.quantities_,'stochastic'),...
  S.quantities_.currentIterate.KKTError(S.quantities_,'true'),...
  S.quantities_.iterationCounter,...
  S.quantities_.innerIterationCounter,...
  S.quantities_.objectiveFunctionEvaluationCounter,...
  S.quantities_.objectiveGradientEvaluationCounter,...
  S.quantities_.constraintFunctionEqualitiesEvaluationCounter,...
  S.quantities_.constraintFunctionInequalitiesEvaluationCounter,...
  S.quantities_.constraintJacobianEqualitiesEvaluationCounter,...
  S.quantities_.constraintJacobianInequalitiesEvaluationCounter,...
  S.quantities_.CPUTime);

end % printFooter