% Copyright (C) 2020 Frank E. Curtis
%
% All Rights Reserved.
%
% Authors: Frank E. Curtis

% DirectionComputationEQPInexact: printIterationValues
function printIterationValues(S,quantities,reporter)

% Get multipliers
[yE,yI] = quantities.currentIterate.multipliers('stochastic');

% Print information
reporter.printf(Enumerations.R_SOLVER,Enumerations.R_PER_ITERATION,...
  ' %+e %+e %+e %+e %s %+e %+e ',...
  norm(quantities.directionPrimal,inf),...
  norm([yE;yI],inf),...
  quantities.currentIterate.KKTError(quantities,'stochastic'),...
  quantities.currentIterate.KKTError(quantities,'true'),...
  quantities.terminationTest,...
  norm(quantities.residualFeasibility,inf),...
  norm(quantities.residualStationarity,inf));

end % printIterationValues