% Copyright (C) 2020 Albert S. Berahas, Frank E. Curtis, Daniel P. Robinson, Baoyu Zhou
%
% All Rights Reserved.

% ParameterComputationFixed: printIterationValues
function printIterationValues(P,quantities,reporter)

% Print iteration values
reporter.printf(Enumerations.R_SOLVER,Enumerations.R_PER_ITERATION,...
  ' %+e %+e %2d %+e %+e',...
  quantities.curvatureParameter,...
  quantities.decompositionParameter,...
  quantities.curvatureIndicator,...
  quantities.meritParameter,...
  quantities.ratioParameter);

end % printIterationValues